### ISSUE TITLE
When using Showkase version 1.0.2 I get this error "error: cannot find symbol - import androidx.room.util.RelationUtil; "

### ISSUE THREAD

**Issue by MaratTursynbek** [airbnb/Showkase#358]
I was using version 1.0.0-beta18 without any issues. When I upgraded to 1.0.2 I started to get this error when trying to compile my project. 

It is strange that these two libraries could affect each other but I thought I need to inform you about this issue. Would be great if you could help me to solve it. Let me know if you need more information.

Dependencies.kt:
```
const val room_version = "2.5.2"
const val showkase_version = "1.0.2"
```

build.gradle.kts:

```
    // Room
    api("androidx.room:room-runtime:$room_version")
    api("androidx.room:room-ktx:$room_version")
    ksp("androidx.room:room-compiler:$room_version")

    // showkase
    implementation("com.airbnb.android:showkase:$showkase_version")
    ksp("com.airbnb.android:showkase-processor:$showkase_version")
```
